# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - 'last 2 versions'
  - 'ie >= 9'
  - 'ios >= 7'

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    # Search for used CSS classes in generated HTML files
    - 'dist/**/*.html'
  ignore:
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: 'dist'
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - 'src/assets/**/*'
    - '!src/assets/{img,js,scss}/**/*'

  # Paths to JavaScript entry points for webpack to bundle modules
  js:
    entries: 'src/assets/js/app.js'
    dist:
      develop: 'dist/assets/js/develop'
      production: 'dist/assets/js/production'
  css:
    entries: './src/assets/scss/app.scss'
    dist:
      develop: 'dist/assets/css/develop'
      production: 'dist/assets/css/production'
  html:
    replace:
      - 'dist/index.html'
      - 'dist/**/*.html'
      - 'dist/**/**/*.html'
  img:
    dev: 'src/assets/img/**/*'
    pro: 'dist/assets/img'
  watch:
    css:
      - 'src/assets/scss/*.scss'
      - 'src/assets/scss/**/*.scss'
    html:
      - './src/pages/**/*.html'
    js:
      - './src/assets/js/*.js'
    img:
      - './src/assets/img/**/*'
